### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aaaaalbert** [CyberSaiyanIT/rhc22-badge#1]
Hi @CyberSaiyanIT, thanks for sharing the repo with us!

Since you asked for PRs for improvements, I wonder what your licensing looks like. I notice that [things in the `components` dir](https://github.com/CyberSaiyanIT/rhc22-badge/blob/master/components/) do include their own licenses, but not the other parts of the repo.

**Comment by CyberSaiyanIT** [comment]
MIT LICENSE defined and applied to the repository. Thank you for reporting it.

**Comment by aaaaalbert** [comment]
Awesome, thanks!

(Closing commit for reference: 2094b25a17eddf7b8e0e201ef3aed1d823f2c212)
